from modules.actors.adversaries.base_adversary import BaseAdversary
from modules.actors.adversaries.greedy_adversary import GreedyAdversary
from modules.actors.adversaries.random_adversary import RandomAdversary
from modules.actors.adversaries.surround_adversary import SurroundAdversary
